export enum BackendRoutes {
  LOGIN = "/auth/login",
  LOGOUT = "/auth/logout",
  REGISTER = "/auth/register",
  GET_USERS = "/auth/getUsers",
  STUDENT_DASHBOARD = "/aluno/dashboard",
  ADMIN = "/admin/painel",
  ADMIN_USERS = "/admin/usuarios",
  ADMIN_SET_TEACHER = "/admin/vincular",
  MOVIE = "/video/data/:videoId",
  TEACHER_DASHBOARD = "/professor/dashboard",
  TEACHER_MATTERS = "/professor/materia/:materiaId",
  LESSON_PROGRESS_UPDATE = "/aula/progresso",
  CLASSROOM_COMPLETED = "/aula/progresso/concluidas",
  CLASSROOM_PROGRESS = "/aula/progresso/:lesson_id",
}
